FROM alpine:latest

RUN apk add --no-cache shadow curl runit openjdk8-jre-base nss

RUN mkdir -p /opt/leshan-bsserver-demo && \
    curl -o /opt/leshan-bsserver-demo/leshan-bsserver-demo.jar \
        https://hudson.eclipse.org/leshan/job/leshan/lastSuccessfulBuild/artifact/leshan-bsserver-demo.jar
RUN useradd -r -d /opt/leshan-server-demo -s /sbin/nologin -U leshan

CMD cd /tmp && \
    chpst -u leshan java -jar /opt/leshan-bsserver-demo/leshan-bsserver-demo.jar \
        --coapport 5783 --coapsport 5784 --webport 8081
